### ISSUE TITLE
Release 2.2.0 is helpful for me, but I have some questions.

### ISSUE THREAD

**Issue by cp3hnu** [s4cha/Stevia#51]
1、Double dash don't support flexible margins
2、Stevia+Fill.swift
```
private func fillH(m points: CGFloat = 0) -> UIView {
        return fill(.Horizontal, points: points)
    }
```
Why "fillH()" function is private?
Thank you for your attention.

**Comment by s4cha** [comment]
@cp3hnu 

1. This is problematic indeed, and will try to add it for next version.

2. fillH got private on purpose to prefer `|view|` syntax over `view.fillH()`

This could be made public again since with fillV() people kind of expect the fillH().

What do you think ?

Thanks a ton for reporting this ;)

**Comment by s4cha** [comment]
@cp3hnu 

1. Is now supported in version 2.2.1
2. `fillH` got renamed into `fillHorizontally` and made public :)

Thanks a lot for taking the time to report those culprits,
Stevia improves thanks to people like you!

**Comment by cp3hnu** [comment]
@s4cha 
Thank you.
