### ISSUE TITLE
Simple Horizontal Alignment Not Working

### ISSUE THREAD

**Issue by someone29926** [s4cha/Stevia#8]
Hi, have just started using your library and am impressed overall!

I did run into one issue fairly early on which I have been as of yet unable to resolve. Even with a very simple horizontal layout I am getting strange results:

let emailInputHolder = UIView()
let emailInput = UITextField()
let emailAddButton = UIButton()

... in render:

emailInput.centerVerticallyInContainer()
emailInput.layer.borderColor = UIColor.lightGrayColor().CGColor
emailInput.layer.borderWidth = 1.0
emailInput.height(30)
emailAddButton.width(75).height(30)

... in layout:

emailInputHolder.layout([
    5,
    |-emailInput-10-emailAddButton-|,
    5
])

Actually the widths seem to get represented as I wanted, BUT the whole thing is pushed all the way to the top of the view and doesn't fit into its intended vertical location at all. 

If I change the layout to |-emailInput-| or |-emailAddButton-| only (for example), they are in the right place vertically but clearly not side by side. It is a little hard to tell from the documentation whether it is required to use alignHorizontally(...) in addition to the layout spec above, but I've tried every iteration I can think of. 

Any assistance would be much appreciated. Can provide more code if helpful...

**Comment by someone29926** [comment]
Here's a screen shot to hopefully help demonstrate. The text field with the "Add" button at the top should be below the "Email Addresses" input text view. Again, if I change nothing but the layout code to remove one of either emailInput or emailAddButton, they end up in the right place vertically. 

![screen shot 2016-02-21 at 10 52 44 pm](https://cloud.githubusercontent.com/assets/1178171/13209101/e2d58708-d8ed-11e5-913e-01e18f32f5cd.png)

**Comment by s4cha** [comment]
Hey @someone29926, first of all thanks for the kind words ;)

The best would be to have all the view code but I'll try my best to help.  

**Multiple horizontal views in one single statement** is not yet supported **in a layout block** at the moment.
Thankfully for you  it's coming very soon and it's actually supported on the `dev` branch.  
In the meantime, what we usually do is break the horizontal layout in multiple statements as such :


```

```swift
layout([
  |-emailAdressesLabel-|,
  |-emailAdressesTextView-|,
  |-emailInput ~ 30
])

emailAddButton.width(75)-| ~ 30
emailInput-10-emailAddButton
alignHorizontally([emailInput,emailAddButton])
```

## dev

As a teaser, here is how you would write it with Stevia 2.0 (dev)
```swift
github "s4cha/Stevia" "dev"
```


```swift
layout([
  |-emailAdressesLabel-|,
  |-emailAdressesTextView-|,
  |-emailInput-10-emailAddButton-| ~ 30
])

// Here ~ 30 is applied to both `emailInput` and `emailAddButton`
// And they are automatically aligned horizontally

// PS: for emailAddButton width you're probably better of using edges insets on button.
// so that if text changes the width would follow ;) 
```

Hope it helps ;)

**Comment by someone29926** [comment]
Thanks @s4cha, I'll give it a go this afternoon and let you know how it turns out!

**Comment by someone29926** [comment]
Success :)

![screen shot 2016-02-22 at 10 10 05 pm](https://cloud.githubusercontent.com/assets/1178171/13240508/15578f96-d9b1-11e5-9c6a-aad0d3570982.png)

Thanks again

**Comment by s4cha** [comment]
Fantastic! @someone29926 if you have anything that you think could improve the api, feel free to reach out  or contribute :)
