### ISSUE TITLE
How to Animate Constraint with Stevia?

### ISSUE THREAD

**Issue by reeichert** [s4cha/Stevia#9]

**Comment by telip007** [comment]
Any solution ?

**Comment by s4cha** [comment]
Hey @reeichert & @telip007 ,

As you may know the usual way to animate a constraint is to change the constant property on it and then call `self.layoutIfNeeded()` in an animation block.

Animating with stevia is no different than native Autolayout 

Here is how you would do it natively :
```swift
// Define and store constraint for later use.
detailTopConstraint = NSLayoutConstraint(item: detail, attribute: .Top, relatedBy: .Equal, toItem: self, attribute: .Top, multiplier: 1, constant: 20)
// Add it
addConstraint(detailTopConstraint)
// [...]
 // Later when you want to change the margin for example :
detailTopConstraint.constant = 100
UIView.animateWithDuration(0.3) {
    self.layoutIfNeeded()
}
```
With Stevia🍃 it becomes :
```swift
detailTopConstraint = c(item: detail, attribute: .Top, toItem: self, constant: 20)
// [...]
// Later
detailTopConstraint.constant = 100
UIView.animateWithDuration(0.3) {
    self.layoutIfNeeded()
}
```
As you see the c() enables you to be more concise as it fills default parameters plus it calls the addConstraint() for you.

The animation part is the exact same because Stevia **is** native Autolayout code.

Issue 6 might help you out as well : https://github.com/s4cha/Stevia/issues/6

Hope it help :)

**Comment by reeichert** [comment]
discussion continues in #6
